org: tapiwam
app: final-py-thumbnail
service: final-py-thumbnail

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  profile: default
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self:provider.region}
    DYNAMODB_TABLE: ${self:custom.dynamoTable}
    THUMBNAIL_BUCKET: ${self:custom.bucket}
  
  iam:
    role:
      name: ${self:service}-${self:provider.stage}-role
      statements:
        - Effect: Allow
          Action: 's3:*'
          Resource: '*'
        - Effect: Allow
          Action: 
            - 'dynamodb:Query'
            - 'dynamodb:PutItem'
            - 'dynamodb:DeleteItem'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:BatchWriteItem'
            - 'dynamodb:BatchGetItem'
            - 'dynamodb:DescribeTable'
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'

custom:
  bucket: tmaruni-thumbnails
  pythonRequirements:
    dockerizePip: true
  dynamoTable: img-url-table

functions:
  s3_thumbnail_generator:
    handler: handler.s3_thumbnail_generator
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:2
      # - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-boto3:4
  list:
    handler: handler.s3_get_thumbnail_urls
    events:
      - http:
          path: images/all
          method: GET
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:2
  get:
    handler: handler.s3_get_thumbnail
    events:
      - http:
          path: images/get/{id}
          method: GET
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:2
  
  delete:
    handler: handler.s3_delete_thumbnail
    events:
      - http:
          path: images/delete/{id}
          method: DELETE
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p311-Pillow:2



plugins:
  - serverless-python-requirements

resources:
  Resources:
    ImagesDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1